apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: prod
type: Opaque
stringData:
  # Do not use these in a real production environment
  DB_USER: "postgres"
  DB_PASSWORD: "YourSuperSecretPassword123"
